# This workflow is written specifically for Jam3/nextjs-boilerplate
# It uploads all contents inside the ./out/ folder generated on build:prod:static process to an AWS S3 account

name: Deploy to S3 Bucket

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
      CONTENTFUL_ENVIRONMENT:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      S3_ORIGIN_BUCKET:
        required: true
  workflow_dispatch:
env:
  tf_working_dir: "./terraform"
  s3_bucket_name: ${{vars.AWS_ACCOUNT_ID}} + "-frontend-react-app"

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        terraform_version: ["1.9.1"]

    steps:    
      - uses: hashicorp/setup-terraform@v3
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws_region: ${{vars.AWS_REGION}}
          aws_profile: ${{vars.AWS_PROFILE}}
          aws_s3_bucket_name: $s3_bucket_name

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: $tf_working_dir
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: $tf_working_dir

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: $tf_working_dir

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: $tf_working_dir
      
  build:
    needs: [create-s3-bucket]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Update NPM
        run: npm install -g npm@8

      - name: Install dependencies
        run: npm ci

      - name: Build NextJS static site
        run: ./.github/scripts/build.sh
        shell: bash
        env:
          CI_ENV: ${{ inputs.CI_ENV }}
          CONTENTFUL_ENVIRONMENT: ${{ inputs.CONTENTFUL_ENVIRONMENT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}

      - name: Deploy
        run: ./.github/scripts/deploy.sh $s3_bucket_name
        shell: bash