name: Build

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - develop
      - staging
      - main
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Update NPM
        run: npm install -g npm@10

      - name: Install dependencies
        run: npm ci

      # TODO Run linters

      - name: Build
        run: ./.github/scripts/build.sh
        shell: bash
